### ISSUE TITLE
set up documentation building

### ISSUE THREAD

**Issue by rabernat** [xgcm/xcape#29]
Here are the steps.

1. First, learn to build the documentation locally. It lives in the `doc` folder. We use [sphinx](https://www.sphinx-doc.org/en/master/). The command to build it is `make html` (from the `doc` folder). To preview your local docs, do `cd _build/html; python -m http.server`.
2. Then configure [readthedocs](https://readthedocs.org/). You will need to create a `.readthedocs.yml` file. ([example](https://github.com/pangeo-data/rechunker/blob/master/.readthedocs.yml))

**Comment by xebadir** [comment]
Took a first crack at this in the branch #32 - successfully did step 1 for initial data, and ran into issues with the building via ReadTheDocs for the forked version as a test due to the fortran dependencies. Guidance I've found online suggests we may need to look at the mock autodocs procedure to deal with this in order to get a successful build. Result of build was this log:
https://readthedocs.org/projects/xcape-test/builds/11707078/?
May also be an issue with the permissions on the Webhooks.

**Comment by chiaral** [comment]
This is done with #36
